#!/bin/sh /etc/rc.common

START=100
STOP=150

start() {
       /usr/bin/node /www/ecr-app/index.js &
        echo "We run NODEJS"
        # commands to launch application
}

boot() {
        start
		uci set firewall.@zone[1].forward='ACCEPT'
		uci delete firewall.@zone[1].network
		uci add_list firewall.@zone[1].network='wwan'
		uci add_list firewall.@zone[1].network='wan'
		uci delete firewall.@zone[0].network
		uci add_list firewall.@zone[0].network='wlan'
		uci add_list firewall.@zone[0].network='usb0'
		uci commit
}

stop() {
        echo stop
        # commands to kill application
}
